### ISSUE TITLE
PDF route not accessible by guest user

### ISSUE THREAD

**Issue by Mathias-Syversen** [amici-infotech/craft-super-pdf#1]
As the title suggests, the PDF is not available to a user that is not logged into Craft.

A 403 is thrown on the url "/super-pdf/*".

![Screenshot 2020-06-16 at 00 35 51](https://user-images.githubusercontent.com/53942798/84712645-650d0380-af69-11ea-8038-73efd6daf780.png)

**Comment by mufi-siebird** [comment]
Can you Share the code?

**Comment by Mathias-Syversen** [comment]
`{% set settings = {
									filename: product.title|replace(' ', '_'),
									type: 'url'
								} %}

								{% set vars = {
									product : product
								} %}

								{% set url = craft.superpdf.template("PDF/product/_template", settings, vars) %}`

**Comment by mufi-siebird** [comment]
Does it work when you not pass `type : 'url'` ?

**Comment by Mathias-Syversen** [comment]
No, chrome tries to open the PDF directly, but says "something went wrong" inside the PDF viewer. It also tries to open the PDF as soon as I enter the page, I need it to be a button on the product page.

**Comment by mufi-siebird** [comment]
Well, When creating PDF, headers change from anything to PDF headers so we can show content in pdf. That means pdf will be an individual page.

I think pdf from html with suit your requirement. I suggest you to not use `type : 'url'` and do something like this.

1. Create new template for pdf. example:  `PDF/product/_template`
Add code like this: https://docs.amiciinfotech.com/craft-cms/super-pdf/frontend/pdf-from-html
2. On your product page, Pass URL to the pdf page. Maybe set a route like this:
`'product/pdf/<slug>' => ['template' => 'PDF/product/_template'],`

For above route URL can be `/product/pdf/my-product-page-url-slug`


Try static demo data first to make sure PDF are rendering.

**Comment by brandondeweese** [comment]
I'm confused. Then what's the use of the "url" option?
