### ISSUE TITLE
Add possibility to configure settings via environment variables

### ISSUE THREAD

**Issue by vaelu** [amici-infotech/craft-super-pdf#10]
A fantastic improvement for the plugin would be, if the general settings (defined in Settings.php) could be defined as environment variables.

For example, if the default file system for saving the PDF files should be a local folder on the development environment, and in the production it is a S3 storage.

**Comment by amici-infotech** [comment]
Hey @vaelu, Its possible even now. All you need to create is a file named `super-pdf.php` and add settings there. I use it like this:
```
<?php
use craft\helpers\App;
use Craft;

return [
    'fontDir' => Craft::getAlias(App::env('FONTS_SYSTEM_PATH')),
    'tempDir' => Craft::getAlias(App::env('FONTS_SYSTEM_PATH')),
    'defaultPaperSize' => 'A4',
    // 'defaultPaperOrientation' => 'landscape',

    'volume' => Craft::getAlias(App::env('PDF_STORAGE_VOLUME')),
];
```

![image](https://user-images.githubusercontent.com/20450552/206724406-afab13f5-f44a-4662-8df9-3eb06bba3ecf.png)
