### ISSUE TITLE
No styles or images

### ISSUE THREAD

**Issue by pixelmachine** [amici-infotech/craft-super-pdf#12]
Just like #4 I'm having no luck loading styles, images, fonts etc. I've tried all the suggestions in the linked issue.

I've used DomPDF with Craft Commerce and Verbb's Plugins and I can always load the images as long as "isRemoteEnabled" is true but Super-PDF is just not working. If I move the CSS into the header then styles will load but external files will not.

Here's my code:

```php
{% set entry = craft.entries.id(entryId).one() %}
  {% set settings = { 
    filename: "#{entry.slug}_#{currentUser.id}", 
    type: 'object',
    isHtml5ParserEnabled: true,
    isRemoteEnabled: true,
    isJavascriptEnabled: true,
    forceDownload: true,
    tempDir: '/tmp',
    fontDir: '/tmp',
  } %}
  {% set vars = { entry : entry } %}
  {% set url = craft.superpdf.template('recipes/print/index', settings, vars) %}
  ```
  
  Where are `tempDir` and `fontDir` relative to? The storage directory? The project root?

**Comment by amici-infotech** [comment]
Hey, did you tried adding the streamContext variable too in super-pdf.php file?

DomPdf needs a tmp path to generate cache fonts and cached files. Thats why we need tmp folders. You can give path of storage folder. Make sure it has write permission.

**Comment by pixelmachine** [comment]
Hey, yep I did try adding `streamContext` and there was no change.

Can you tell me where are `tempDir` and `fontDir` relative to? For example if I set `tempDir: '/tmp'` where is that?

i.e. relative to project:
`projectRoot/tmp`
`projectRoot/storage/tmp`

Or relative to system:
`~/tmp`
`/tmp`

Assume the former but I never see those created.

**Comment by amici-infotech** [comment]
It would be absolute path so /tmp means root /tmp. Some servers doesnt allow to load files outside of project dir and thus the /tmp folder not works. You try something like this

rtrim($_SERVER[“DOCUMENT_ROOT”], “/“) . “/../storage/super-pdf/tmp”

it should create folder automatically there if storage folder have write permission

**Comment by pixelmachine** [comment]
Even if I hardcode it doesn't work. 

Nothing in the tmp directory. The tmp directory is not created. No styles in the pdf.

Full config:
```php
return [
    'streamContext' => [
        'ssl' => [
            'allow_self_signed'=> true,
            'verify_peer' => false,
            'verify_peer_name' => false,
        ],
    ],
    'isHtml5ParserEnabled' => true,
    'isRemoteEnabled' => true,
    'isJavascriptEnabled' => true,
    'forceDownload' => true,
    'pdfBackend' => 'auto',
    'fontDir' => '/[full-path]/craft/storage/super-pdf/font',
    'tempDir' => '/[full-path]/craft/storage/super-pdf/tmp',
];
```

**Comment by amici-infotech** [comment]
very strange. Is there a way you can share an FTP access to me to investigate into your server? (staging).
You can send me sensitive information on email at contact@amiciinfotech.com

**Comment by pixelmachine** [comment]
Not at the moment.

However I think that I've started to find the issue.

This line in Pdf.php I think is wrong:

```php
if(! empty($this->settings->streamContext))
{
    $this->dompdf->setHttpContext(stream_context_create($this->settings->streamContext));
}
```

Dompdf accepts an array ([see here](https://github.com/dompdf/dompdf/pull/2807)), so this is how it should be:

```php
$this->dompdf->setHttpContext([
    'ssl' => [
        'verify_peer' => false, 
        'allow_self_signed' => true, 
        'verify_peer_name' => false
    ]
]);
```

Charging this has allowed images to load. Still no luck with CSS or fonts but it's a start.

**Comment by pixelmachine** [comment]
Yep, it's all working now.

Dompdf is very fussy with CSS, getting the fonts and CSS to work took a lot of trial and error. I moved the CSS inline into the head and had to be pretty careful about correctly assigning fonts.
