### ISSUE TITLE
Multiple files created

### ISSUE THREAD

**Issue by AbbeyDesign** [amici-infotech/craft-super-pdf#15]
I am using this code to create files but it repeatedly creates new files in a loop. 

```
{% set settings = {
		filename: ''~theEntry.lastName~'-'~theEntry.firstName~'-Statement',
		isHtml5ParserEnabled: true,
		isRemoteEnabled : true,
		type: 'object',
		volume: "230324",
		folder: theEntry.related[0].slug ?? 'unassigned'~'/'~theEntry.slug,
} %}


{% set object = craft.superpdf.template("p/dx/xx/_entry", settings, vars) %}
```

If I set to reset behavior to "overide" the file just replaces itself every two minutes. If it is set to "duplicate" it creates a new file every two minutes resulting in endless files. I have to quit out of my browser and shut down the local server to stop it.

Also my que manager has hundreds of "Updating search indexes" pending jobs.

**Comment by amici-infotech** [comment]
I didnt understand, where you put the code where its running for every two minutes and in a loop? Can you try to explain the whole situation?

**Comment by AbbeyDesign** [comment]
It's not in a loop. It just keeps creating a new file over and over again. I think it might have to do with another plugin, async-que... I am investigating.

**Comment by amici-infotech** [comment]
As it should be, a file should definately create when a CODE triggers. either to create new file each time or override it, You can also set to `ignore` where if file already exists, it wont create it again.

**Comment by AbbeyDesign** [comment]
I mean it keeps creating a new file over and over again once the template is open. Ignore stops this, but there will be cases where the pdf should be updated so ignore is not ideal. I would need overide.

Duplicate creates hundreds of files
Overide limits to one file, but the timestamp keeps changing every couple of minutes(so it keeps overiding itself)

**Comment by AbbeyDesign** [comment]
After further investigation this was, as suspected, due to the Async Que plugin. The fix can be found here if anyone has the same issue.

[https://github.com/ostark/craft-async-queue#configuration-optional](url)
