### ISSUE TITLE
Is this Plugin made to be working with Craft 4.x?

### ISSUE THREAD

**Issue by LeoWie93** [amici-infotech/craft-super-pdf#17]
We are trying to use this Plugin right now but have multiple issues.

Is it made for Craft 4? Because the description just mentions Craft 3.

**Comment by amici-infotech** [comment]
Plugin is upgraded to Craft 4. Can you let me know what kind of issues you are facing?

**Comment by LeoWie93** [comment]
Thanks for the quick reply!

We are using a loop over entries to generate multiple different pdfs to download by url

## Ignore if already exists
If using the "ignore" option for already existing files. It would use the url of the first pdf generated for following pdf generation.

I could fix this by adding two lines to the `Pdf.php` => `html` function:

``` php
public function html($html = "", $settings = [])
    {
        $this->asset = null;
        $this->dompdf = null;

        foreach ($settings as $key => $value) {
            $this->settings[$key] = $value;
        }
        $this->fetchFile();

        $this->html = $html;

        return $this->_generate();

    }
```

The member variable `$asset` was never reset and so it would always find / return the first generated asset this page load.
Resulting in all url's being the one of the first.

- though this only happens when working with a clean pdf dir. So no pdf's have yet been generated


## On Change
If im seeing correct, the plugin does not have a way to link entries to pdfs. So we would need to delete pdf's ourself to let them be regenerated

**Comment by amici-infotech** [comment]
@LeoWie93 Makes sense. variable was not reseting. I never thought someone will need it to create loop based multiple pdf. lol.

I have upgraded plugin. it should work now.

ON CHANGE method. Yes, you manually need to clear that PDF to create new ones.

**Comment by vaelu** [comment]
We get the following error since version `2.0.2.4`:
`Cannot assign null to property amici\SuperPdf\libraries\Pdf::$dompdf of type Dompdf\Dompdf`

I added null type on line 24 in Pdf.php and it works:
`public Dompdf|null $dompdf;`

**Comment by amici-infotech** [comment]
@vaelu thanks for headsup. fixed
