### ISSUE TITLE
Deprecation error in Craft Utilities

### ISSUE THREAD

**Issue by tomkiss** [amici-infotech/craft-super-pdf#18]
Small thing, but there's a non-critical deprecation warning in Craft's Deprecation Warnings utility in the Control Panel:

```
Deprecation error: PDF Settings type: url setting has been deprecated. Use type: object instead.
Called from /var/www/html/vendor/amici/craft-super-pdf/src/libraries/Pdf.php:226
```

**Comment by mufi-paragonn** [comment]
It seems like you are using URL type in your PDF. that function is deprecated and replaced by object. You should use something like this:

```
{% set settings = {
    filename: "My_PDF",
    type: 'object',
} %}

{% set vars = {
    entry : entry,
    data : data
} %}

{% set object = craft.superpdf.template("template/_pdf_template", settings, vars) %}

// Default echo object will return URL
{{ object }}

{{ object.url }}
{{ object.getUrl() }}

{{ object.path }}
{{ object.getPath() }}

{{ object.filename }}
{{ object.getFilename() }}

{{ object.kind }}
{{ object.size }}
{{ object.dateModified|date("m/d/Y H:i:s") }}

// Returns craft assets element. Only if PDF is stored in craft assets volumes instead of storage folder.
{{ object.asset }}
{{ object.getAsset() }}
```

where in previous `type: 'url'`, code was returning only URL of pdf, with above code `type: 'object'`, it returns model object from which you can get lot more information than just a URL.

**Comment by amici-infotech** [comment]
It seems like you are using URL type in your PDF. that function is deprecated and replaced by object. You should use something like this:

```
{% set settings = {
    filename: "My_PDF",
    type: 'object',
} %}

{% set vars = {
    entry : entry,
    data : data
} %}

{% set object = craft.superpdf.template("template/_pdf_template", settings, vars) %}

// Default echo object will return URL
{{ object }}

{{ object.url }}
{{ object.getUrl() }}

{{ object.path }}
{{ object.getPath() }}

{{ object.filename }}
{{ object.getFilename() }}

{{ object.kind }}
{{ object.size }}
{{ object.dateModified|date("m/d/Y H:i:s") }}

// Returns craft assets element. Only if PDF is stored in craft assets volumes instead of storage folder.
{{ object.asset }}
{{ object.getAsset() }}
```

where in previous `type: 'url'`, code was returning only URL of pdf, with above code `type: 'object'`, it returns model object from which you can get lot more information than just a URL.

**Comment by tomkiss** [comment]
Great, thanks for that!

I think [the documentation](https://docs.amiciinfotech.com/craft-cms/super-pdf/frontend/pdf-from-template) may need an update to reflect this change 👍
