### ISSUE TITLE
Footer page number duplication

### ISSUE THREAD

**Issue by samroberts707** [amici-infotech/craft-super-pdf#19]
I'm trying to add a page number to the bottom of every page in the PDF, pages are created automatically so I can't just hard-code these in.

I'm using PHP to generate these page numbers:

```
           <footer>
            <script type="text/php">
                if ( isset($pdf) ) {
                    $x = 72;
                    $y = 800;
                    $text = "{PAGE_NUM} of {PAGE_COUNT}";
                    $font = $fontMetrics->get_font("Helvetica", "normal");
                    $size = 9;
                    $color = array(0.2, 0.2, 0.2);
                    $word_space = 0.0;  //  default
                    $char_space = 0.0;  //  default
                    $angle = 0.0;   //  default
                    $pdf->page_text($x, $y, $text, $font, $size, $color, $word_space, $char_space, $angle);
                }
            </script>
        </footer>
```
Making the footer element position: fixed; Adds it to the bottom of every page, but the PAGE_COUNT variable is printed multiple times on top of itself making it impossible to read.

![Screenshot 2023-06-22 at 12 03 45](https://github.com/amici-infotech/craft-super-pdf/assets/7763311/6af30ce5-4706-44cb-80cd-a8c00aea11db)

**Comment by amici-infotech** [comment]
Hey, Did you check by removing all css? or create a plain pdf without all the context in with just bunch of text?

With the same code as yours, I get this:

![image](https://github.com/amici-infotech/craft-super-pdf/assets/20450552/2ffecde2-0ef6-40dd-b122-586bd6dc6d44)
