### ISSUE TITLE
getAcceptsJson() on string

### ISSUE THREAD

**Issue by maxtovvvvvv** [amici-infotech/craft-super-pdf#2]
I'm getting the following error when I want to generate a pdf URL:

**_Call to a member function getAcceptsJson() on string_**

This is my code:

```

{% set settings = {
            filename: "My_PDF",
            type: 'url'
        } %}

        {% set vars = {

        } %}

        {% set url = craft.superpdf.template("/_components/forms/submissions/pdf", settings) %}

        <a href="{{ url }}">download</a>


```
Any way I can fix this?

Thanks!

**Comment by amici-infotech** [comment]
Hi, this issue has been resolved in v1.0.3. Please upgrade the addon and let me know if you have any other queries.

Thanks!
Mufi
[Amici Infotech Support]
