### ISSUE TITLE
Syntax Error, Unexpected '|'

### ISSUE THREAD

**Issue by smockensturm** [amici-infotech/craft-super-pdf#21]
`syntax error, unexpected '|', expecting variable (T_VARIABLE)`

~/vendor/amici/craft-super-pdf/src/libraries/Pdf.php

line 24
`public Dompdf|null $dompdf`

This line is causing an error and rendering all our current Super PDF installs useless.

PHP 7.4.33
Craft 3.9.1
SuperPDF 1.0.8.6

**Comment by mufi-paragonn** [comment]
The syntax you've mentioned, `public Dompdf|null $dompdf`, is an example of PHP attribute (also known as annotations) syntax that was introduced in PHP 8.

I recommend to use latest version of PHP as lastest craft 3 does support php 8, but plugin should run with php 7 too so I have fixed that attribution. Can you try upgrading plugin to 1.0.8.7.

**Comment by amici-infotech** [comment]
The syntax you've mentioned, `public Dompdf|null $dompdf`, is an example of PHP attribute (also known as annotations) syntax that was introduced in PHP 8.

I recommend to use latest version of PHP as lastest craft 3 does support php 8, but plugin should run with php 7 too so I have fixed that attribution. Can you try upgrading plugin to 1.0.8.7.

**Comment by smockensturm** [comment]
Good to go. Thank you very much.
