### ISSUE TITLE
PDF Settings Type Deprecation Warning 

### ISSUE THREAD

**Issue by harrylindemann** [amici-infotech/craft-super-pdf#22]
I am seeing the following deprecation message:

`PDF Settings type: url setting has been deprecated. Use type: object instead.`
`/var/www/html/vendor/amici/craft-super-pdf/src/libraries/Pdf.php:125`

Would you be able to have a look? 

Thank you

**Comment by amici-infotech** [comment]
This is Duplicaiton of this. https://github.com/amici-infotech/craft-super-pdf/issues/18

We have removed `url` type and replace it with `object`. Benifit of it is that it returns whole object with following variables:

```
filename
kind
size
dateModified
path
url
```

If you have set Craft's asset folder as storage path in settings, it will returns `Assets` element object.

**Comment by harrylindemann** [comment]
Got it, thank you! I was using the sample code from the [Docs](https://docs.amiciinfotech.com/craft-cms/super-pdf/frontend/pdf-from-template ) section.

**Comment by amici-infotech** [comment]
I will update the DOCS. Thanks to point that out.
