### ISSUE TITLE
PDF generates fine locally but inline SVG images outputs text 'image not found or type unknown'

### ISSUE THREAD

**Issue by clintonbeattie** [amici-infotech/craft-super-pdf#27]
Locally I am using inline svg images on a non-secure local URL. The PDF generates fine but when uploading to a staging server it returns 'image not found or type unknown'. Have there been any previous mentions of this happening?

Thank you

**Comment by amici-infotech** [comment]
Can you get me code you are using? also, is your staging site is http authentication protected? sometimes image do not generates because its CURL agent is not able to download image because of security.

**Comment by clintonbeattie** [comment]
Thank you. Currently testing authentication as we do have some on server. Also looking into the tmp folder generation.

**Comment by clintonbeattie** [comment]
I can confirm that it was http authentication causing the issue. Many thanks
