### ISSUE TITLE
Some missing features we would like

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [amici-infotech/craft-super-pdf#7]
Hi, We like this plugin and are considering using this for a coming project and maybe more in the future. However we are missing 2 important features (Or i cant find them). We'd like a page count option so like on the bottom right corner "1 of 12". Also we would like to set a basic template with a brand on it and maybe some basic styling that gets repeated for every page. 
Is this something you are looking to add in the future or not?

Thanks in advance!
Kind regards,

Bob van Velzen
PixelDeluxe

**Comment by amici-infotech** [comment]
Hey. Point 1 is a great feature to be add. We will surely add that.

For Point 2, I am not sure what you want to do with core features of super pdf with that. I mean, you can add any css styles you want to in your pdfs. that means, you can create a theme that will repeat in every page all by just few css stuff.

**Comment by bob-pixeldeluxe** [comment]
Hi, Thats great. How can we create this theme is there like a html tag that repeats around every page's data so we can set a background image there? We want to place the brand of our customer's company on the top right corner. We are printing a big matrix so the pages are added automatically we are not creating every page individually at the moment.

Thanks in advance!

**Comment by amici-infotech** [comment]
Well, I would do something like this:

```
{% set html %}
    <html>
    <head>
        <style>
            @page { margin: 100px 25px; }
            header { position: fixed; top: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
            footer { position: fixed; bottom: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
            p { page-break-after: always; }
            p:last-child { page-break-after: never; }
        </style>
    </head>
    <body>
        <header><h1 style="margin-top: 10px; margin-left: 15px; font-size: 24px;">Some Header Branding</h1></header>
        <footer>footer on each page</footer>
        <main>
            <p>page1</p>
            <p>page2</p>
        </main>
    </body>
    </html>
{% endset %}

{% set settings = {
    filename: "My_PDF",
} %}

{{ craft.superpdf.html(html, settings) }}
```

**Comment by bob-pixeldeluxe** [comment]
Hi, Ah i was not aware position fixed elements would be repeated for every page thats perfect. Thanks for the quick response.

**Comment by bob-pixeldeluxe** [comment]
@amici-infotech Hi we want to use this plugin again for a different website is there any update on the automatic page count?

**Comment by amici-infotech** [comment]
hi. We have released version v5.0.1 that does the counter and page total both. Here is the example on how you can use it.:

```
{% set html %}
<!doctype html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style>
            @page { margin: 100px 25px; }
            .page-break { page-break-after: always; }
            .page-break:last-child { page-break-after: never; }
            header { position: fixed; top: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
            footer { position: fixed; bottom: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }

            #footer {
                position: fixed;
                left: 20px;
                bottom: 0;
                text-align: center;
                }
            #footer .page:after {
                content: counter(page);
            }
        </style>
    </head>
<body>
    <header><h1 style="margin-top: 10px; margin-left: 15px; font-size: 24px;">Some Header Branding</h1></header>

    <footer>
        <p>Page <span class="page"></span> of SUPER_PDF_TOTAL_PAGES</p>
    </footer>

    <div class="page-break"><p>Lorem ipsum dolor sit amet</p></div>
    <div class="page-break"><p>Lorem ipsum dolor sit amet</p></div>
    <div class="page-break"><p>Lorem ipsum dolor sit amet</p></div>
    <div class="page-break"><p>Lorem ipsum dolor sit amet</p></div>
        <div class="page-break"><p>Lorem ipsum dolor sit amet</p></div>
        <div class="page-break"><p>Lorem ipsum dolor sit amet</p></div>
        <div class="page-break"><p>Lorem ipsum dolor sit amet</p></div>
        <div class="page-break"><p>Lorem ipsum dolor sit amet</p></div>
        <div class="page-break"><p>Lorem ipsum dolor sit amet</p></div>
</body>
</html>
{% endset %}
{% set settings = {
    filename: "My_PDF",
    type: 'object'
} %}
{% set object = craft.superpdf.html(html, settings) %}
{# {{ html | raw }} #}
<iframe src="{{ object.getUrl() }}" frameborder="0" width="1000" height="2000"></iframe>
```

**Comment by bob-pixeldeluxe** [comment]
Hi, 

So the current page count works correctly for me but wherever i place "SUPER_PDF_TOTAL_PAGES" it will just render that as a string.  It does work when i show it inside an iframe as in your example. but we want to use either the browser pdf view or the download.

Our code: 
`{% set html %}
		<!doctype html>
		<html>
			<head>
				<meta http-equiv="Content-Type" content="charset=utf-8" />
				<style type="text/css">
					@font-face {
						src: url({{ siteUrl  }}public/fonts/Inter-Regular.ttf) format('truetype');
						font-family: "Inter Regular";
						font-weight: 400;
						font-style: normal;
					}

					@font-face {
						src: url({{ siteUrl  }}public/fonts/Inter-SemiBold.ttf) format('truetype');
						font-family: "Inter SemiBold";
						font-weight: 600;
						font-style: normal;
					}

					table, tbody, tr {
						width: 600px;
						vertical-align: top;
					}

					* {
						font-family: "Inter Regular";
						color: #093F7A;
					}


					#brand {
						position:  fixed;
						top:  0px;
						left:  0px;
						height:  70px;
					}

					body {
						padding-top:  80px;
						padding-bottom:  40px;
					}

					p, li, a {
						font-family: "Inter Regular";
						font-size: 16px;
						line-height: 20px;
					}

					h1,h2,h3,h4,h5,h6 {
						font-family: "Inter SemiBold";
						font-weight:  600;
					}

					.first-title {
						margin-top: 0px;
					}

					h1 {
						font-size: 54px;
						line-height: 59px;
					}

					h2 {
						font-size: 45px;
						line-height: 49px;
					}

					h3 {
						font-size: 37px;
						line-height: 41px;
					}

					h4 {
						font-size: 31px;
						line-height: 34px;
					}

					h5 {
						font-size:  26px;
						line-height:  28px;
					}

					#footer {
						position: fixed;
						bottom: 0px;
						left: 0px;
						opacity:  0.5;
					}

					#footer p {
						margin-bottom: 0px;
					}

					footer .page:after {
		                content: counter(page);
		            }
				</style>
			</head>

			<img id="brand" src="{{ siteUrl }}public/img/logo.png" alt="">

			<div id="footer">
				<p>Kooijman Autar Notarissen Straatweg 7 3051 BA Rotterdam</p>
			</div>

			<footer>
		        <p>Page <span class="page"></span> of SUPER_PDF_TOTAL_PAGES</p>
		    </footer>

			<body>
				<h2 class="first-title">Title</h2>

		  		<p>
		  			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  		</p>

		  		<p>
		  			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  		</p>

		  		<p>
		  			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  		</p>

		  		<p>
		  			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  		</p>

		  		<p>
		  			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  		</p>

		  		<p>
		  			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  		</p>
			</body>
	    </html>
	{% endset %}

	{% set settings = {
	    filename: 'page title here',
	    defaultFont: 'Inter Regular',
	    fontDir: "/tmp",
		tempDir: "/tmp"
	} %}


	{% set html = html|replace({
	    "![CDATA[YII-BLOCK-HEAD]]>" : "",
	    "<![CDATA[YII-BLOCK-HEAD]]>" : "",
	    "<![CDATA[YII-BLOCK-BODY-BEGIN]]>" : "",
	    "<![CDATA[YII-BLOCK-BODY-END]]>" : ""
	}) %}

	{{ craft.superpdf.html(html, settings) }}`

**Comment by amici-infotech** [comment]
@bob-pixeldeluxe I suggest you to upgrade plugin to the latest version. This feature was added for Plugin:

Craft 3: 1.1.1
Craft 4: 2.0.2.6
Craft 5: 5.0.1

**Comment by bob-pixeldeluxe** [comment]
@amici-infotech Hi, Yes I have the example I sent previously does not work on 5.0.1. Your iframe variant does.

**Comment by amici-infotech** [comment]
Seems like it does work. Is that correct output?

![image](https://github.com/amici-infotech/craft-super-pdf/assets/20450552/b67f3e61-fa06-4146-a1b8-01eaff3b9e34)

![image](https://github.com/amici-infotech/craft-super-pdf/assets/20450552/dbf3eaac-7a82-4b62-b9e1-521c47ec9450)

**Comment by amici-infotech** [comment]
Is that a possibility where you are loading cached version of PDF? happens when you have setting set to:
![image](https://github.com/amici-infotech/craft-super-pdf/assets/20450552/69b2cc37-8e40-4503-8ed9-01d6ddd5659f)
